package org.orinocoX509.entity.field.certificate;

public enum FieldType
{
    AUTHORITY_INFORMATION_ACCESS, AUTHORITY_KEY_IDENTIFIER, BASIC_CONSTRAINT, CERTIFICATE_POLICY, CRL_DISTRIBUTION_POINT, DEVICE_TYPE, EXTENDED_KEY_USAGE, ISSUER, ISSUER_ALTERNATIVE_NAME, KEY_USAGE, NETSCAPE_CERTIFICATE_TYPE, QUALIFIED_CERTIFICATE_STATEMENT, SUBJECT, SUBJECT_ALTERNATIVE_NAME, SUBJECT_DIRECTORY_ATTRIBUTE, SUBJECT_KEY_IDENTIFIER
}
